package lsd.cucumber.report.verify;

import lsd.cucumber.report.LsdReportPage;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verify the reports generated by the LsdCucumberPlugin in the build/reports/lsd directory after processing the cucumber
 * scenarios.
 */
public class BasicScenarioReportShould {
    private static final LsdReportPage LSD_REPORT_PAGE = new LsdReportPage("Scenario.html");

    @AfterAll
    static void cleanup() {
        LSD_REPORT_PAGE.close();
    }

    @Test
    public void containAPageTitle() {
        assertThat(LSD_REPORT_PAGE.title()).isEqualTo("scenario");
    }

    @Test
    public void containAScenarioTitle() {
        var articleTitles = LSD_REPORT_PAGE.articleTitles();

        assertThat(articleTitles)
                .hasSize(1)
                .contains(
                        "Basic scenario"
                );
    }

//    @Test
//    public void generatesArticlesForEachExampleRowInAScenarioOutline() {
//
//        var articleTitles = page.locator("main > article > h2").allTextContents();
//
//        assertThat(page.title()).isEqualTo("scenario_outline");
//        assertThat(articleTitles)
//                .hasSize(2)
//                .contains(
//                        "Scenario with a data table #1",
//                        "Scenario with a data table #2"
//                );
//    }

//    @Test
//    public void generateDataTablePage() {
//        navigateToLsdReport();
//
//        var articleTitles = page.locator("main > article > h2").allTextContents();
//
//        assertThat(page.title()).isEqualTo("data_table");
//        assertThat(articleTitles)
//                .hasSize(1)
//                .contains(
//                        "Scenario with a data table"
//                );
//    }

}
